image:
  repository: 881217801864.dkr.ecr.us-east-1.amazonaws.com/fn-drupal-operator
  tag: successive38
  pullPolicy: Always

istio:
  enabled: false

realm: ""

customerECR: 881217801864.dkr.ecr.us-east-1.amazonaws.com
customerECRRepoNamePrefix: customer

watchNamespace: ""
useDynamicProvisioning: ""
defaultStorageClass: "efs"
newrelicDaemonAddr: newrelic.acquia-polaris-system.svc.cluster.local:9999
