apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: drupalapplications.fnresources.acquia.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.numEnvironments
    name: Envs
    type: integer
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: fnresources.acquia.io
  names:
    kind: DrupalApplication
    listKind: DrupalApplicationList
    plural: drupalapplications
    shortNames:
    - drapps
    - drapp
    singular: drupalapplication
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: DrupalApplication is the Schema for the drupalapplications API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: DrupalApplicationSpec defines the desired state of a Drupal
            Application
          properties:
            gitRepo:
              type: string
            imageRepo:
              type: string
          required:
          - gitRepo
          type: object
        status:
          description: DrupalApplicationStatus defines the observed state of a Drupal
            Application
          properties:
            environments:
              items:
                description: DrupalEnvironmentRef defines a reference to a DrupalEnvironment
                properties:
                  environmentID:
                    type: string
                  name:
                    type: string
                  namespace:
                    type: string
                  uid:
                    description: UID is a type that holds unique ID values, including
                      UUIDs.  Because we don't ONLY use UUIDs, this is an alias to
                      string.  Being a type captures intent and helps make sure that
                      UIDs and names do not get conflated.
                    type: string
                required:
                - name
                - namespace
                - uid
                type: object
              type: array
            numEnvironments:
              format: int32
              type: integer
          required:
          - numEnvironments
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
