apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sites.fnresources.acquia.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.status
    name: status
    type: string
  - JSONPath: .spec.domains
    name: domains
    type: string
  - JSONPath: .spec.tls
    name: tls
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  group: fnresources.acquia.io
  names:
    kind: Site
    listKind: SiteList
    plural: sites
    singular: site
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Site is the Schema for the sites API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SiteSpec defines the desired state of Site
          properties:
            certIssuer:
              type: string
            database:
              type: string
            domains:
              items:
                type: string
              type: array
            environment:
              type: string
            ingressClass:
              type: string
            install:
              description: Information to install the site
              properties:
                adminEmail:
                  type: string
                adminUsername:
                  type: string
                installProfile:
                  type: string
              required:
              - adminEmail
              - adminUsername
              - installProfile
              type: object
            tls:
              type: boolean
          required:
          - database
          - domains
          - environment
          type: object
        status:
          description: SiteStatus defines the observed state of Site
          properties:
            domains:
              type: string
            status:
              description: Status describes the status of the site.
              type: string
          required:
          - domains
          - status
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
