---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: fn-drupal-operator
  name: fn-drupal-operator-webhook
spec:
  ports:
  - name: appwebhook
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    name: fn-drupal-operator
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: fn-drupal-operator-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: fn-drupal-operator-webhook-cert
spec:
  dnsNames:
  - fn-drupal-operator-webhook
  - fn-drupal-operator-webhook.{{ .Release.Namespace }}
  - fn-drupal-operator-webhook.{{ .Release.Namespace }}.svc
  - fn-drupal-operator-webhook.{{ .Release.Namespace }}.svc.cluster.local
  secretName: fn-drupal-operator-webhook-cert
  issuerRef:
    name: fn-drupal-operator-issuer
---
# Deprecated in v1.16 in favor of admissionregistration.k8s.io/v1
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: fn-drupal-operator-validator
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/fn-drupal-operator-webhook-cert
webhooks:
- name: drupalapplications.fnresources.acquia.io
  rules:
  - apiGroups:   ["fnresources.acquia.io"]
    apiVersions: ["v1alpha1"]
    operations:  ["CREATE", "UPDATE"]
    resources:   ["drupalapplications"]
  clientConfig:
    caBundle: Cg==
    service:
      namespace: {{ .Release.Namespace }}
      name: fn-drupal-operator-webhook
      path: /validate-fnresources-acquia-io-v1alpha1-drupalapplication
- name: databases.fnresources.acquia.io
  rules:
  - apiGroups:   ["fnresources.acquia.io"]
    apiVersions: ["v1alpha1"]
    operations:  ["CREATE", "UPDATE"]
    resources:   ["databases"]
  clientConfig:
    caBundle: Cg==
    service:
      namespace: {{ .Release.Namespace }}
      name: fn-drupal-operator-webhook
      path: /validate-fnresources-acquia-io-v1alpha1-database
  failurePolicy: Fail
---
# Deprecated in v1.16 in favor of admissionregistration.k8s.io/v1
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: fn-drupal-operator-validator
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/fn-drupal-operator-webhook-cert
webhooks:
- name: databases.fnresources.acquia.io
  rules:
  - apiGroups:   ["fnresources.acquia.io"]
    apiVersions: ["v1alpha1"]
    operations:  ["CREATE"]
    resources:   ["databases"]
  clientConfig:
    caBundle: Cg==
    service:
      namespace: {{ .Release.Namespace }}
      name: fn-drupal-operator-webhook
      path: /mutate-fnresources-acquia-io-v1alpha1-database
  failurePolicy: Fail
